"""
Translates a JSON file containing the CFG of a smart contract to the Coq representation of the FORYU project
(https://github.com/costa-group/foryu/tree/main)
JSON are obtained using solc:
$ solc file_standard_input.json --standard-json --pretty-json > cfg.json
"""

import json
import pprint

"""
Layout of the JSON file
{
    'contracts':{
        'name.sol':{
          'entry'
            'yulCFGJson':{
                'entry1':{
                    'blocks': [],
                    'functions': {
                        'f1': ...
                        'f2': ...
                    } 
                },
                
                'entry2':{
                    'blocks': [],
                    'functions': {
                        'f1': ...
                        'f2': ...
                    } 
                } 
            } 
            ...
        }
    }
    
    'errors':...
}
"""


def gen_name(prefix):
    """ Generates a name from the prefix """
    return "__".join(prefix)


def process_blocks(blocks, prefix):
    """ Generates a main function from an objects blocks """
    # TODO: add parameters and return value
    if blocks:
        return {gen_name(prefix + ['main']):
                    {'arguments': [],
                     'blocks': blocks,
                     'entry': blocks[0]['id'],
                     'numReturns': 0}
                }
    return {}


def process_object(d: dict, prefix: list):
    """ Extracts all the entries in an object (and recursively subobjects), generating functions for each one """
    r = {}
    for object_name in d:
        if object_name == 'type':
            continue

        subobj = d[object_name]['subObjects']
        if subobj:
            r.update(process_object(subobj, prefix + [object_name]))
        r.update(d[object_name]['functions'])  # TODO: Do we need to rename the functions in different objects? (prefix)
        blocks = d[object_name]['blocks']
        if blocks:
            r.update(process_blocks(blocks, prefix + [object_name]))

    return r


def process_json(path):
    """ Processes a JSON file as generated by solc and generates a flat dictionary of function definitions """
    with open(path, 'r', encoding="utf-8") as f:
        data = json.load(f)

    scs = data['contracts']
    r = {}
    for sc_filename in scs:
        sc = scs[sc_filename]
        for comp in sc:
            yulcfg = sc[comp]['yulCFGJson']
            assert yulcfg['type'] == 'Object'
            r.update(process_object(yulcfg, [sc_filename, comp]))

    return r


if __name__ == '__main__':
    pprint.pp(process_json('constant_variables_standard_input.json_cfg.json'))
